# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5c6d7e14fbeac20d206042aae291f2042c6696e580d024be73450051fbb985cfe7c0247e66f22115830e64694189334f11108a6e41dd5d5bab4b1214c69044df

test:
  secret_key_base: 4fda0f5531118a1313fde2633bdc20abfd182eb42edeef4e089a4542a1e3074407310cd6e18a856be641bfc6ecb41947d3c96e5d019305e0d7662df7245fe3d8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
